name: Fork Sync Bot

on:
  schedule:
    - cron: "0 9 * * *"   # every day at 9:00 UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout this repo
      - name: Checkout bot repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      # Debug to ensure secret exists
      - name: Debug BOT_TOKEN secret
        run: |
          if [ -z "${{ secrets.BOT_TOKEN }}" ]; then
            echo " BOT_TOKEN secret is NOT available"
            exit 1
          else
            echo " BOT_TOKEN secret is set"
          fi

      # Run sync bot
      - name: Run sync bot
        env:
          GITHUB_OWNER: USD-AI-ResearchLab   # your org name
          GITHUB_TOKEN: ${{_
