name: Fork Sync 

on:
  schedule:
    - cron: '0 6 * * *'   # Run every day at 6 AM UTC
  workflow_dispatch:

env:
  GITHUB_OWNER: USD-AI-ResearchLab   # change to your GitHub username if repos are under your account

jobs:
  sync-forks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout sync bot repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install PyGithub requests
        
    - name: Run sync bot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # ✅ fixed
        GITHUB_OWNER: ${{ env.GITHUB_OWNER }}
      run: |
        python sync_bot.py
