name: Fork Sync Bot

on:
  schedule:
    - cron: "0 9 * * *"   # run every day at 9:00 UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bot repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests

      - name: Debug BOT_TOKEN
        run: |
          if [ -z "${{ secrets.BOT_TOKEN }}" ]; then
            echo " BOT_TOKEN is empty"
            exit 1
          else
            echo " BOT_TOKEN is available"
          fi

      - name: Run sync bot
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GITHUB_OWNER: USD-AI-ResearchLab
        run: |
          python sync_bot.py
