name: Fork Sync Bot

on:
  schedule:
    - cron: "0 6 * * *"   # every day at 6 AM UTC
  workflow_dispatch:

env:
  GITHUB_OWNER: USD-AI-ResearchLab

jobs:
  sync-forks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bot repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install PyGithub requests

      - name: Run sync bot
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GITHUB_OWNER: ${{ env.GITHUB_OWNER }}
        run: |
          python sync_bot.py
