name: Fork Sync

on:
  schedule:
    # Always 11:20 AM America/Chicago (DST-aware) using two UTC crons
    - cron: "20 16 * * *"   # 11:20 during CDT (UTC-5)
    - cron: "20 17 * * *"   # 11:20 during CST (UTC-6)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      # Make tokens visible to the Python script
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FORK_SYNC_TOKEN: ${{ secrets.FORK_SYNC_TOKEN }}
      GITHUB_OWNER: USD-AI-ResearchLab
      GIT_TERMINAL_PROMPT: "0"

    steps:
      - name: Run only at 11:20 America/Chicago
        run: |
          if [ "$(TZ=America/Chicago date +%H:%M)" != "11:20" ]; then
            echo "Not 11:20 America/Chicago; exiting."
            exit 0
          fi

      - name: Checkout bot repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub pyyaml

      - name: Configure git identity
        run: |
          git config --global user.name "usd-ai-sync-bot"
          git config --global user.email "bot@ai-research-lab.org"

      - name: Verify required files
        run: |
          test -f sync_bot.py || (echo "::error::sync_bot.py missing"; exit 1)
          test -f repos.yml   || (echo "::error::repos.yml missing"; exit 1)

      - name: Hardening git (no extra headers, no prompts)
        run: |
          git config --global credential.helper ""
          git config --global http.https://github.com/.extraheader ""

      - name: Run sync bot
        run: python sync_bot.py
